### ISSUE TITLE
Why not use the latest version of triton ?

### ISSUE THREAD

**Issue by chaoming0625** [jax-ml/jax-triton#171]
I found this repo needs ``triton==2.0.0.dev20221202``, why not use the latest triton version? How to make the ``jax-triton`` compatible with the triton latest version?

**Comment by sharadmv** [comment]
jax-triton at HEAD is compatible with a very recent Triton. Since Triton hasn't done a release in a while, we're unable to make a release pinned to a recent Triton. Check out the version pins in `pyproject.toml`.

**Comment by chaoming0625** [comment]
OK, thank you @sharadmv. I installed a nightly version of ``triton`` and it works.
