### ISSUE TITLE
How do "num_warps" and "num_stages" mean?

### ISSUE THREAD

**Issue by chaoming0625** [jax-ml/jax-triton#2]
Dear all, I notice that ``triton_call()``  function receives ``num_warps`` and ``num_stages`` arguments. And they are different in "add.py" and "matrix_multiplication.py" examples. How do they mean? How can we provide them when customize an CUDA operator?

**Comment by sharadmv** [comment]
These parameters come directly from the Triton compiler which is documented [here](https://github.com/openai/triton/blob/3e2953f3570acc807f975eee58f1565483841b72/python/triton/code_gen.py#L1339-L1345). Copy pasting from there:

```
num_warps: the number of warps to use for the kernel when compiled for GPUs. For example, if
                      `num_warps=8`, then each kernel instance will be automatically parallelized to
                      cooperatively execute using `8 * 32 = 256` threads.
num_stages: the number of stages that the compiler should use when software-pipelining loops.
                       Mostly useful for matrix multiplication workloads on SM80+ GPUs.
```

A warp is a collection of 32 threads executed in parallel by a stream executor (SM) so `num_warps` controls the amount of parallelism to be used. `num_stages` is a parameter for the Triton compiler that I'm less familiar with.

**Comment by chaoming0625** [comment]
Dear @sharadmv , thanks for your reply. I got it.
