### ISSUE TITLE
`jax-triton` in Google Colab

### ISSUE THREAD

**Issue by leandrolcampos** [jax-ml/jax-triton#207]
I'm trying to run the `add_kernel` example in Google Colab, using an NVIDIA Tesla T4 GPU with CUDA v11.8.89.

Everytime I call `add(x_val, y_val)`, I get a `XlaRuntimeError` with the following message:

> XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: ptxas exited with non-zero error code 65280, output: ptxas /tmp/tempfile-b4023cedd8a0-bb9aba3b-452-601567fa49fa3, line 5; fatal : Unsupported .version 8.0; current version is '7.8'
ptxas fatal   : Ptx assembly aborted due to errors
; current tracing scope: custom-call.3; current profiling annotation: XlaModule:#hlo_module=jit_triton_kernel_call,program_id=4#.

Please see this notebook for more information:
https://gist.github.com/leandrolcampos/fbdac327dbc7399c1d58d8b929dbeb67

Is it possible to run `jax-triton` in Google Colab? If yes, how? I tried different installation options presented in the documentation, but nothing worked.

All the best,

**Comment by sharadmv** [comment]
This might be due to a lack of Triton support for older GPUs. I may not have time to reproduce it this week but it might be trying it with vanilla Triton to confirm it.

**Comment by leandrolcampos** [comment]
Hi @sharadmv,

Thank you for your response. And congratulations on this project!

Please take a look at this second notebook:
https://gist.github.com/leandrolcampos/a9ac4d01bf73b379dc6ee33edc279940

As you suggested, I initially atempted to use the `add_kernel` kernel with Triton + Torch (and it worked). Then I tried it with Jax-Triton + JAX, but I got the same `XlaRuntimeError` error.

Now, please see this third notebook:
https://gist.github.com/leandrolcampos/6da6b551f2a27dcf608975b2a12f1b4b

When I imported Triton, Torch, Jax, and Jax-Triton in the same cell, I got the following error when I tried to use `add_kernel` kernel with Triton + Torch:

> AttributeError: 'NoneType' object has no attribute 'loader'

All the best,

**Comment by sharadmv** [comment]
I was able to get JAX-Triton/Pallas working in a Colab. Check out the discussion here: https://github.com/google/jax/discussions/17367#discussioncomment-6880177
