### ISSUE TITLE
Referenced JAX version does not (yet) include jax.experimental.pallas

### ISSUE THREAD

**Issue by markschoene** [jax-ml/jax-triton#214]
The jax version referenced in the 'pyproject.toml' does not yet include jax.experimental.pallas as required by jax_triton/utils.py (line 16) as of August 2.

"jax @ git+https://github.com/google/jax@9a21ff0780d1a16adf35b22dd7521e2804833760",

**Comment by sharadmv** [comment]
Thanks for the heads up. I'll update the pin today.
