### ISSUE TITLE
Add support for runtime scalar kernel inputs (i.e. non-constexpr).

### ISSUE THREAD

**Issue by chr1sj0nes** [jax-ml/jax-triton#57]
Triton supports runtime scalar inputs, but these are not exposed by jax-triton. For example, in Triton's matmul example, `m`, `n`, and `k` are all runtime inputs, but in the jax-triton example they are `constexpr`. This forces a recompile, even though there is negligible runtime performance benefit.

**Comment by sharadmv** [comment]
This is a limitation of the XLA custom calls mechanic IIUC. The custom call can only provide GPU buffer pointers.

We should ask for this to be supported.

**Comment by chr1sj0nes** [comment]
I think we should be able to encode these values in the opaque data on the custom call. I'll try to come up with a design.

**Comment by sharadmv** [comment]
Yea that will work.

Worth keeping in mind that at least in the future, in a JAX+dynamic shapes world, we'd want to be able to pass dynamic scalars into the kernel as well. That will require an XLA change.

**Comment by sharadmv** [comment]
Fixed in #65
